Variables
There are ten variables in the dataset as follows:

REF (reference number). The highest REF numbers were the last entries made. They are not unique values
Company name or manufacturer
Company location (Country)
Date of review of the chocolate ratings
Origin of bean (Country)
Specific bean origin or bar name
Cocoa percent
Ingredients: Represents the number of ingredients in the chocolate; (B = Beans, S = Sugar, S* = Sweetener other than white cane or beet sugar, C = Cocoa Butter, V = Vanilla, L = Lecithin, Sa = Salt)
Most memorable characteristics
Rating

Lecithin: a natural emulsifier found in egg yolks, soybeans, and sunflower seeds. It's added to chocolate to change its texture and consistency. It keeps the cocoa butter and cream from separating and improves its flow properties.

In [1]:
import pandas as pd

df = pd.read_csv('chocolate_bar_ratings_2022.csv')
df

,REF,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,2454,5150,U.S.A.,2019,Tanzania,"Kokoa Kamili, batch 1",76%,"3- B,S,C","rich cocoa, fatty, bready",3.25
1,2454,5150,U.S.A.,2019,Madagascar,"Bejofo Estate, batch 1",76%,"3- B,S,C","cocoa, blackberry, full body",3.75
2,2458,5150,U.S.A.,2019,Dominican Republic,"Zorzal, batch 1",76%,"3- B,S,C","cocoa, vegetal, savory",3.50
3,2542,5150,U.S.A.,2021,Fiji,"Matasawalevu, batch 1",68%,"3- B,S,C","chewy, off, rubbery",3.00
4,2542,5150,U.S.A.,2021,India,"Anamalai, batch 1",68%,"3- B,S,C","milk brownie, macadamia,chewy",3.50
...,...,...,...,...,...,...,...,...,...,...
2583,1205,Zotter,Austria,2014,Blend,Raw,80%,"4- B,S*,C,Sa","waxy, cloying, vegetal",2.75
2584,1996,Zotter,Austria,2017,Colombia,"APROCAFA, Acandi",75%,"3- B,S,C","strong nutty, marshmallow",3.75
2585,2036,Zotter,Austria,2018,Blend,"Dry Aged, 30 yr Anniversary bar",75%,"3- B,S,C","fatty, earthy, cocoa",3.00
2586,2170,Zotter,Austria,2018,Congo,Mountains of the Moon,70%,"3- B,S,C","fatty, mild nuts, mild fruit",3.25
2587,2170,Zotter,Austria,2018,Belize,Maya Mtn,72%,"3- B,S,C","muted, roasty, accessible",3.50

In [ ]:
# Getting an overview of the dataset in the next few cells
df.head()

,REF,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,2454,5150,U.S.A.,2019,Tanzania,"Kokoa Kamili, batch 1",76%,"3- B,S,C","rich cocoa, fatty, bready",3.25
1,2454,5150,U.S.A.,2019,Madagascar,"Bejofo Estate, batch 1",76%,"3- B,S,C","cocoa, blackberry, full body",3.75
2,2458,5150,U.S.A.,2019,Dominican Republic,"Zorzal, batch 1",76%,"3- B,S,C","cocoa, vegetal, savory",3.50
3,2542,5150,U.S.A.,2021,Fiji,"Matasawalevu, batch 1",68%,"3- B,S,C","chewy, off, rubbery",3.00
4,2542,5150,U.S.A.,2021,India,"Anamalai, batch 1",68%,"3- B,S,C","milk brownie, macadamia,chewy",3.50

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2588 entries, 0 to 2587
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   REF                               2588 non-null   int64
 1   Company (Manufacturer)            2588 non-null   str
 2   Company Location                  2588 non-null   str
 3   Review Date                       2588 non-null   int64
 4   Country of Bean Origin            2588 non-null   str
 5   Specific Bean Origin or Bar Name  2588 non-null   str
 6   Cocoa Percent                     2588 non-null   str
 7   Ingredients                       2501 non-null   str
 8   Most Memorable Characteristics    2588 non-null   str
 9   Rating                            2588 non-null   float64
dtypes: float64(1), int64(2), str(7)
memory usage: 202.3 KB

In [4]:
df.shape

(2588, 10)

In [ ]:
print(df.dtypes)
# These data types look appropriate. I might want to change the Cocoa Percent to an integer for plotting purposes.

Company (Manufacturer)                  str
Company Location                        str
Review Date                           int64
Country of Bean Origin                  str
Specific Bean Origin or Bar Name        str
Cocoa Percent                           str
Ingredients                             str
Most Memorable Characteristics          str
Rating                              float64
dtype: object

In [ ]:
# Checking for null values.  There are 2588 rows, and the Ingredients column has 87 null values according to 
# df.info() above. Need to find out which ones.
df.isnull()

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2583,False,False,False,False,False,False,False,False,False
2584,False,False,False,False,False,False,False,False,False
2585,False,False,False,False,False,False,False,False,False
2586,False,False,False,False,False,False,False,False,False
2587,False,False,False,False,False,False,False,False,False

In [ ]:
# Checking for null values. There are 2588 rows, and the Ingredients column has 87 null values according to 
# df.info() above. Need to find out which ones.
df.isna()

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2583,False,False,False,False,False,False,False,False,False
2584,False,False,False,False,False,False,False,False,False
2585,False,False,False,False,False,False,False,False,False
2586,False,False,False,False,False,False,False,False,False
2587,False,False,False,False,False,False,False,False,False

In [ ]:
# This tells us that the missing values are in the ingredients column. Tells us the same thing as df.info()
df.isna().any()

Company (Manufacturer)              False
Company Location                    False
Review Date                         False
Country of Bean Origin              False
Specific Bean Origin or Bar Name    False
Cocoa Percent                       False
Ingredients                          True
Most Memorable Characteristics      False
Rating                              False
dtype: bool

In [ ]:
# Find which rows are missing data in the Ingredients column.
null_rows = df[df['Ingredients'].isnull()]
print(null_rows)

              Company (Manufacturer) Company Location  Review Date  \
88                     Amazing Cacao           Russia         2017
89                     Amazing Cacao           Russia         2017
167              Artisan du Chocolat             U.K.         2010
303                           Bonnat           France         2006
330           Bouga Cacao (Tulicorp)          Ecuador         2009
...                              ...              ...          ...
2478  Vintage Plantations (Tulicorp)           U.S.A.         2007
2479  Vintage Plantations (Tulicorp)           U.S.A.         2007
2480  Vintage Plantations (Tulicorp)           U.S.A.         2007
2505                      Whittakers      New Zealand         2011
2515                  Willie's Cacao             U.K.         2013

     Country of Bean Origin   Specific Bean Origin or Bar Name Cocoa Percent  \
88                     Peru                            Maranon           70%
89                     Peru                        Platan Bajo           70%
167               Venezuela                          Venezuela          100%
303                   Blend                        One Hundred          100%
330                 Ecuador            El Oro, Hacienda de Oro          100%
...                     ...                                ...           ...
2478                Ecuador  Los Rios, Rancho Grande 2004/2007          100%
2479                Ecuador  Los Rios, Rancho Grande 2004/2007           90%
2480                Ecuador  Los Rios, Rancho Grande 2004/2007           75%
2505                  Ghana                              Ghana           72%
2515              Indonesia             Java, Indonesian Black          100%

     Ingredients    Most Memorable Characteristics  Rating
88           NaN                  raisins, pungent    3.00
89           NaN  few grits, blackcherry, licorice    3.50
167          NaN           very nutty, very bitter    1.75
303          NaN               acidic, bitter, dry    1.50
330          NaN    cardboard, very bitter, floral    1.50
...          ...                               ...     ...
2478         NaN  bland, mild fruit, strong bitter    2.00
2479         NaN         some fruit, strong bitter    2.00
2480         NaN      cocoa,earthy,very astringent    3.00
2505         NaN    sticky, dry, vanilla dominates    2.50
2515         NaN       fruit, strong smoke, bitter    2.25

[87 rows x 9 columns]

Handling missing data
1. Fill in the missing ingredients with the most common value. 
B, S, C (Beans, Sugar, Cocoa Butter) = 39.7% 
B, S (Beans, Sugar) = 28%
B, S, C, L (Beans, Sugar, Cocoa Butter, Lecithin) =  11%
These three unique value combinations together comprise 78.7% of the rows in the dataset.

2. Drop the rows with missing values. I would be dropping 3.3% of the dataset. 

3. Fill in the missing values with 'unknown' or 'not provided' for missing strings.

I think I will replace the missing values with 'unknown' since it's only one column. I'd still like to include these rows in charts for cocoa percentage, bean country, manufacturer country, ratings, etc.

I could even see if there are trends within this small subset of missing-ingredients data. 

Numeric data isn't missing, so I don't think it will skew results in any way.

In [ ]:
# Checking the number of occurrences of each unique combination of ingredients in the ingredients column
df['Ingredients'].value_counts()

Ingredients
3- B,S,C          1029
2- B,S             738
4- B,S,C,L         293
5- B,S,C,V,L       184
4- B,S,C,V         141
2- B,S*             31
4- B,S*,C,Sa        20
3- B,S*,C           13
3- B,S,L             8
4- B,S*,C,V          7
5-B,S,C,V,Sa         6
1- B                 6
4- B,S,V,L           5
4- B,S,C,Sa          5
6-B,S,C,V,L,Sa       4
3- B,S,V             3
4- B,S*,V,L          3
4- B,S*,C,L          2
3- B,S*,Sa           1
2- B,C               1
5- B,S,C,L,Sa        1
Name: count, dtype: int64

In [ ]:
# Checking the number of entries for each country
df['Country of Bean Origin'].value_counts()

Country of Bean Origin
Venezuela             254
Peru                  248
Dominican Republic    234
Ecuador               223
Madagascar            184
                     ...
China                   1
Principe                1
Sulawesi                1
Suriname                1
DR Congo                1
Name: count, Length: 63, dtype: int64

In [ ]:
# Checking the number of occurrences of each manufacturer
df['Company (Manufacturer)'].value_counts()

Company (Manufacturer)
Soma                    57
Fresco                  39
Arete                   32
Bonnat                  30
A. Morin                29
                        ..
Vietcacao (A. Morin)     1
Vintage Plantations      1
Whittakers               1
Xocolat                  1
Zacharias                1
Name: count, Length: 593, dtype: int64

In [ ]:
# Number of occurrences for each unique combination of characteristics. 
df['Most Memorable Characteristics'].value_counts()

Most Memorable Characteristics
spicy, cocoa                    4
creamy, nutty, cocoa            4
sweet, vanilla, cocoa           3
sweet, marshmallow              3
sandy, sweet, cocoa             3
                               ..
waxy, cloying, vegetal          1
strong nutty, marshmallow       1
fatty, earthy, cocoa            1
fatty, mild nuts, mild fruit    1
muted, roasty, accessible       1
Name: count, Length: 2545, dtype: int64

In [15]:
df['Company Location'].value_counts()

Company Location
U.S.A.                   1168
France                    179
Canada                    178
U.K.                      134
Italy                      79
                         ...
Wales                       1
Martinique                  1
St.Vincent-Grenadines       1
Ghana                       1
Suriname                    1
Name: count, Length: 65, dtype: int64

In [9]:
df.describe()

               REF  Review Date       Rating
count  2588.000000  2588.000000  2588.000000
mean   1459.185471  2014.545209     3.198319
std     773.852201     4.082722     0.444069
min       5.000000  2006.000000     1.000000
25%     820.000000  2012.000000     3.000000
50%    1470.000000  2015.000000     3.250000
75%    2122.000000  2018.000000     3.500000
max    2768.000000  2022.000000     4.000000

In [10]:
df['Cocoa Percent'].value_counts()

Cocoa Percent
70%       1070
75%        312
72%        309
65%         93
80%         90
68%         75
74%         69
73%         67
60%         46
71%         44
77%         43
85%         40
64%         37
76%         35
67%         35
66%         28
78%         22
100%        21
82%         18
55%         16
62%         16
63%         15
69%         13
90%          9
88%          8
58%          8
61%          7
81%          6
83%          5
72.50%       4
84%          4
91%          3
73.50%       2
79%          2
71.50%       2
56%          2
89%          2
99%          2
50%          1
86%          1
42%          1
60.50%       1
57%          1
46%          1
53%          1
87%          1
Name: count, dtype: int64

In [11]:
print(df['Specific Bean Origin or Bar Name'])

0                 Kokoa Kamili, batch 1
1                Bejofo Estate, batch 1
2                       Zorzal, batch 1
3                 Matasawalevu, batch 1
4                     Anamalai, batch 1
                     ...
2583                                Raw
2584                   APROCAFA, Acandi
2585    Dry Aged, 30 yr Anniversary bar
2586              Mountains of the Moon
2587                           Maya Mtn
Name: Specific Bean Origin or Bar Name, Length: 2588, dtype: str

I dropped the REF column because I didn't think it had any relevance to the analysis. It appears to be just a number that specifies when the entry was made. The highest REF numbers were the last entries made.

In [12]:
df = df.drop('REF', axis = 1)
df

,Company (Manufacturer),Company Location,Review Date,Country of Bean Origin,Specific Bean Origin or Bar Name,Cocoa Percent,Ingredients,Most Memorable Characteristics,Rating
0,5150,U.S.A.,2019,Tanzania,"Kokoa Kamili, batch 1",76%,"3- B,S,C","rich cocoa, fatty, bready",3.25
1,5150,U.S.A.,2019,Madagascar,"Bejofo Estate, batch 1",76%,"3- B,S,C","cocoa, blackberry, full body",3.75
2,5150,U.S.A.,2019,Dominican Republic,"Zorzal, batch 1",76%,"3- B,S,C","cocoa, vegetal, savory",3.50
3,5150,U.S.A.,2021,Fiji,"Matasawalevu, batch 1",68%,"3- B,S,C","chewy, off, rubbery",3.00
4,5150,U.S.A.,2021,India,"Anamalai, batch 1",68%,"3- B,S,C","milk brownie, macadamia,chewy",3.50
...,...,...,...,...,...,...,...,...,...
2583,Zotter,Austria,2014,Blend,Raw,80%,"4- B,S*,C,Sa","waxy, cloying, vegetal",2.75
2584,Zotter,Austria,2017,Colombia,"APROCAFA, Acandi",75%,"3- B,S,C","strong nutty, marshmallow",3.75
2585,Zotter,Austria,2018,Blend,"Dry Aged, 30 yr Anniversary bar",75%,"3- B,S,C","fatty, earthy, cocoa",3.00
2586,Zotter,Austria,2018,Congo,Mountains of the Moon,70%,"3- B,S,C","fatty, mild nuts, mild fruit",3.25
2587,Zotter,Austria,2018,Belize,Maya Mtn,72%,"3- B,S,C","muted, roasty, accessible",3.50

In [33]:
# Check for duplicates
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2583    False
2584    False
2585    False
2586    False
2587    False
Length: 2588, dtype: bool

In [ ]:
# Show duplicate rows, since above output is truncated. 
# In this case, there are no duplicate rows. It returned an empty dataframe.
duplicate_rows = df[df.duplicated()]
print(duplicate_rows)

Empty DataFrame
Columns: [Company (Manufacturer), Company Location, Review Date, Country of Bean Origin, Specific Bean Origin or Bar Name, Cocoa Percent, Ingredients, Most Memorable Characteristics, Rating]
Index: []

In [ ]:
.iloc and .loc

In [ ]:
.sort_values

In [ ]:
df.groupby()